// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://atiugbqrcuatlrdpxpry.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aXVnYnFyY3VhdGxyZHB4cHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MTIxMTIsImV4cCI6MjA3NDk4ODExMn0.AkrtUBl_UHhUm9XPx6kmdVfgHDQ-wX9KCgGQPczfDTU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});